name: Backend - Main CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: production

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: gwijkuop78-
          POSTGRES_DB: banco_mensal
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar o JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Instalar dependências
        run: mvn install -DskipTests

      - name: Executar testes
        run: mvn test

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Build e Run do Docker localmente
        run: |
          CONTAINER_NAME=springboot-backend

          echo "Parando e removendo container antigo (se existir)..."
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          echo "Buildando a imagem Docker..."
          docker build --no-cache -t $CONTAINER_NAME .

          echo "Iniciando container..."
          docker run -d -p 8080:8080 --env-file .env --name $CONTAINER_NAME $CONTAINER_NAME
